# ------------- 单数据源配置 single ------------------
#spring:
#  # datasource 相关配置
#  datasource:
#    url: jdbc:mysql://119.45.56.227:3306/testdb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  # jpa 相关配置
#  # 具体可参考 JpaProperties.java
#  jpa:
#    hibernate:
#      ddl-auto: validate # create
#    database: mysql
#    show-sql: true

# ------------------- 多数据源配置 multi -------------------
#spring:
#  # 数据源配置 DataSourceProperties
#  datasource:
#    primary:
#      jdbc-url: jdbc:mysql://119.45.56.227:3306/testdb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
#      username: root
#      password: 123456
#      driver-class-name: com.mysql.cj.jdbc.Driver
#
#    secondary:
#      jdbc-url: jdbc:mysql://119.45.56.227:3306/testdb2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
#      username: root
#      password: 123456
#      driver-class-name: com.mysql.cj.jdbc.Driver
#
#  # jpa 配置
#  jpa:
#    hibernate:
#      ddl-auto: create
#    database: mysql
#    show-sql: true

# ----------------------- 分布式事务配置 jta -------------------------
spring:
  datasource:
    primary:
      # jdbc-url --> url
      url: jdbc:mysql://119.45.56.227:3306/testdb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver

    secondary:
      url: jdbc:mysql://119.45.56.227:3306/testdb2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver

  # jpa 配置
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: mysql
    show-sql: true
  # jta 配置
  jta:
    atomikos:
      datasource:
        max-pool-size: 20
        borrow-connection-timeout: 60
      connectionfactory:
        max-pool-size: 20
        borrow-connection-timeout: 60