spring:
  # datasource 相关配置
  datasource:
    url: jdbc:mysql://119.45.56.227:3306/testdb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  # jpa 相关配置
  # 具体可参考 JpaProperties.java
  jpa:
    hibernate:
      ddl-auto: create-drop
      database: mysql